# Generated by Django 5.0.1 on 2024-01-31 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='bot.message')),
            ],
        ),
    ]
