# Generated by Django 5.0.1 on 2024-01-31 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='bot.message'),
        ),
    ]
